name: Check PR
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: determine the new added project
        id: determine_project
        run: |
          # Get the name of the main branch (assuming it's 'main')
          MAIN_BRANCH="main"

          # Fetch the main branch
          git fetch origin $MAIN_BRANCH:$MAIN_BRANCH

          # Get the latest commit diff or the diff between the current branch and the main branch
          DIFF=$(git diff --name-status $MAIN_BRANCH)

          # Extract the names of new folders
          if [[ -z "$(echo \"$DIFF\" | grep \"^A\" | awk '{print $2}' | grep 'Cargo.toml' | awk -F/ '{print $1}' | uniq)" ]]; then
            echo "No new project found - skipping the build"
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          fi

          NEW_FOLDERS=$(echo "$DIFF" | grep "^A" | awk '{print $2}' | grep 'Cargo.toml' | awk -F/ '{print $1}' | uniq)

          # Set the output variable
          echo "::set-output name=project::$NEW_FOLDERS"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: setup | rust
        uses: dtolnay/rust-toolchain@stable
        with:
          default: true
          profile: minimal
      - name: build
        run: cargo build --release
        working-directory: ${{ steps.determine_project.outputs.project }}

      - name: test
        run: cargo run --release -- ../samples/input-small.csv > results-small.txt
        working-directory: ${{ steps.determine_project.outputs.project }}

      - name: diff results
        run: |
          # Check if the results are correct
          diff -w results-small.txt ../samples/expected-results-small.txt

        working-directory: ${{ steps.determine_project.outputs.project }}

      - name: setup | hyperfine
        uses: taiki-e/install-action@v2
        with:
          tool: hyperfine

      - name: benchmark
        run: |
          hyperfine --warmup 5 --export-markdown benchmark.md \
            'cargo run --release -- ../samples/input-small.csv' \
            'cargo run --release -- ../samples/input-medium.csv' \
            'cargo run --release -- ../samples/input-large.csv'
        working-directory: ${{ steps.determine_project.outputs.project }}

      - name: post comment
        run: |
          # Read the test results
          RESULTS=$(cat ${{ steps.determine_project.outputs.project }}/benchmark.md)

          # Print the results
          echo "Results: $RESULTS"

          GITSHA=$(git rev-parse HEAD)

          echo "### Benchmark Preview at $GITSHA" > comment.md
          echo "" >> comment.md
          echo "$RESULTS" >> comment.md
          echo "" >> comment.md

          # Post the comment to the PR
          gh pr comment ${{ github.event.pull_request.number }} -F comment.md
        env:
          GH_TOKEN: ${{ github.token }}
